### ISSUE TITLE
Can we have  a button/option to change  the Files position to Navigation Drawer?

### ISSUE THREAD

**Issue by Premjit-Chowdhury** [itsaky/AndroidIDE#10]
Can we  have a button/option to change the Files position to Navigation Drawer?
Because for a developer it is important to navigate his/her app directories or files easily and comfortably but in the AndroidIDE app directories/files navigation option on a FAB button which takes 2clicks to open but on the other hand if this is implemented in Navigation Drawer then with only a single swipe we can open the directories/files and it takes less time as compared to FAB.
So, if you implement this feature suggestion to AndroidIDE than it will be very much beneficial to navigate files/directories.
Thank You.

**Comment by itsaky** [comment]
It is actually a navigation drawer. You could simply swipe from right edge of the screen to the left to open the files navigation.

**Comment by Premjit-Chowdhury** [comment]
Oops! Thanks for the feedback.
