### ISSUE TITLE
[FEATURE]: Asked to build task when the project opened

### ISSUE THREAD

**Issue by asm-blahblah** [itsaky/AndroidIDE#107]
In recent version, IDE will automatically build the task once the user opened the project. I don't think it's have to so
please ask confirmation dialogs before did that.

**Comment by BanDroid** [comment]
It cant be like that, if you stop the gradle daemon at the start, then many features in editor wouldn't work, like autocompletion, error logs, and any other stuff.

**Comment by asm-blahblah** [comment]
I don't know about the error logs and any other stuff but autocompletion for the editor didn't parse anything from the builds dir so

**Comment by stayaway49** [comment]
@BanDroid Yeah. I was trying to say the same thing.

**Comment by itsaky** [comment]
The auto-completion depends on the build that is executed when you open a project. It is needed to get the dependencies. The details about the project is provided to the IDE in [`:app:initializeIDEProject`](https://github.com/itsaky/AndroidIDE/blob/dec31920b698bc621a1733a96982a8b68161cac6/app/src/main/java/com/itsaky/androidide/services/builder/IDEService.java#L170) task. Then the dependencies are provided to the language server. See [this](https://github.com/itsaky/AndroidIDE/blob/dec31920b698bc621a1733a96982a8b68161cac6/app/src/main/java/com/itsaky/androidide/handlers/BuildServiceHandler.java#L85) and [this](https://github.com/itsaky/AndroidIDE/blob/dec31920b698bc621a1733a96982a8b68161cac6/app/src/main/java/com/itsaky/androidide/EditorActivity.java#L848).

**Comment by asm-blahblah** [comment]
ahh okay
