### ISSUE TITLE
Bugs noticed after gradle failed

### ISSUE THREAD

**Issue by Premjit-Chowdhury** [itsaky/AndroidIDE#11]
https://user-images.githubusercontent.com/72644801/134456971-b7eb028f-1fb4-4a91-9c90-fca4a7bc1cd6.mp4

Checkout this video 👆
![Screenshot_2021-09-23-10-36-01-493_com itsaky androidide](https://user-images.githubusercontent.com/72644801/134457143-e3142776-9671-4a81-a7bd-ad162bc0b85d.jpg)
Top left corner Back Arrow not working👆

**Comment by itsaky** [comment]
These are known issues. They are fixed in v1.0.3-alpha which will be released soon.

**Comment by Premjit-Chowdhury** [comment]
Any estimate time for release version 1.0.3 ???

**Comment by itsaky** [comment]
v1.0.3-alpha has a lot of changes. We have to test them all. Most probably, it'll be released in next 1-2 weeks.

**Comment by Premjit-Chowdhury** [comment]
Thanks for the info.
