### ISSUE TITLE
The war in Ukraine

### ISSUE THREAD

**Issue by Wendors** [itsaky/AndroidIDE#113]
Sign this petition in order to block the aggressor in Ukraine, namely Russia, which is killing civilians !!!

https://www.change.org/p/github-ban-github-for-russian-developers?recruiter=1256399662&utm_source=share_petition&utm_medium=twitter&utm_campaign=psf_combo_share_initial&utm_term=f118353c9f6c40b88ede1805af9914f2&recruited_by_id=b2b9bf50-9d43-11ec-a960-c97fd5c6080e

**Comment by itsaky** [comment]
Not the right place dude...
