### ISSUE TITLE
[FEATURE]: Unable to swipe-open file tree

### ISSUE THREAD

**Issue by TimScriptov** [itsaky/AndroidIDE#114]
Android 12
![Screenshot_20220307-190341.png](https://user-images.githubusercontent.com/31324315/157049156-d6ea746d-32f8-458c-b73d-c1d1620def96.png)
The file manager does not open due to swipes

**Comment by itsaky** [comment]
Try swiping from upper right portion of the screen.
I'll add a `MenuItem` in the options menu for the file tree.

**Comment by TimScriptov** [comment]
@itsaky thx, working
