### ISSUE TITLE
Gradle error: Unknown reloc type

### ISSUE THREAD

**Issue by aufarakha** [itsaky/AndroidIDE#116]
-------------------- NOTE --------------------
Gradle Wrapper is not available!
Installing default one. Gradle v7.3 will be downloaded if necessary.
----------------------------------------------
========== [14:39:19] TASK_BEGIN: assembleDebug ==========
Error: dl failure on line 598
Error: failed ROOT/framework/jdk/lib/server/libjvm.so, because dlopen failed: unknown reloc type 17 @ 0xeb5d4680 (72164)
Gradle process exited with exit code 6

========== [14:39:23] TASK_BEGIN: assembleDebug ==========
Error: dl failure on line 598
Error: failed ROOT/framework/jdk/lib/server/libjvm.so, because dlopen failed: unknown reloc type 17 @ 0xe78d4680 (72164)
Gradle process exited with exit code 6

**Comment by aufarakha** [comment]
@itsaky

**Comment by itsaky** [comment]
It is an issue with 32-bit JDK 11. Use JDK 17 instead.

**Comment by aufarakha** [comment]
How to download jdk17(i mean where to download jdk17 32 bit)
Like in terminal in androidIDE or in google

**Comment by itsaky** [comment]
Use terminal (`pkg in openjdk-17`).

**Comment by aufarakha** [comment]
Reading package lists... Done
Building dependency tree... Done
E: Unable to locate package openjdk-17

Already tried apt upgrade/update it's never work :(

**Comment by bo0t** [comment]
It has been worked on my phone ..
I was facing the same error 
Open the terminal and type :
pkg install openjdk-17

**Comment by BanDroid** [comment]
> Reading package lists... Done
> Building dependency tree... Done
> E: Unable to locate package openjdk-17
> 
> Already tried apt upgrade/update it's never work :(
> 
> Should I download in termux and move it to storage then use your terminal to copy jdk from storage to /data/user/yourpackageapk(because I forget i check soon)/files/framework

I think what you should do is

```
pkg up
```

Instead of apt update/upgrade.
Have you try it?

**Comment by bo0t** [comment]
> > Reading package lists... Done
> > Building dependency tree... Done
> > E: Unable to locate package openjdk-17
> > Already tried apt upgrade/update it's never work :(
> > Should I download in termux and move it to storage then use your terminal to copy jdk from storage to /data/user/yourpackageapk(because I forget i check soon)/files/framework
> 
> I think what you should do is
> 
> ```
> pkg up
> ```
> 
> Instead of apt update/upgrade. Have you try it?

I installed openjdk-17 successfuly but ain't nothing changes
after typing 'java' on the terminal or back to build output 
It's still the same error

**Comment by bo0t** [comment]
@BanDroid

**Comment by Marklhouise02** [comment]
Same issue :-(
