### ISSUE TITLE
[BUG]Overlapping floating text actions and AndroidIDE isn't responding 

### ISSUE THREAD

**Issue by Premjit-Chowdhury** [itsaky/AndroidIDE#129]
See this👇
https://user-images.githubusercontent.com/72644801/159125411-dc3acc60-9e24-400c-9094-1308fc0f4855.mp4

And this also👇

![Screenshot_2022-03-19-19-50-04-557_com itsaky androidide](https://user-images.githubusercontent.com/72644801/159125444-c6606bb6-7f12-467b-ad0c-f9a15cb49233.jpg)

**Comment by MrIkso** [comment]
@itsaky maybe use ActionMode.Callback2[ActionMode.Callback2](https://developer.android.com/reference/android/view/ActionMode.Callback2)

**Comment by itsaky** [comment]
The overlapping issue has been fixed. But can't reproduce the ANR issue. Is there any way to reproduce it?

**Comment by Premjit-Chowdhury** [comment]
This pic belongs to old androidide beta version apk but in latest beta 2.0.2 apk this issue is fixed however i have faced this issue only one time when i first time open androidIde project  .

I think as for now you can close this issue.

**Comment by itsaky** [comment]
Okay. If you face this issue again, reopen the issue.
