### ISSUE TITLE
I tried the IDE several times - always unsuccessfully 

### ISSUE THREAD

**Issue by thewolfprod** [itsaky/AndroidIDE#138]
**Describe the bug**
I tried the application and contributed to issues about bugs - Available solutions for errors only make the situation worse. 

Currently getting same errors again (same as few Months ago and to this day i can't fix them - I do not know if I omit something or it is just the fault of the application) 

**Errors:**
_After updating openjdk, editing ide-env.props..._

After createing project, first build (unsuccesful), restart app, build once again just to get that:
https://pastebin.com/Tv5NxFsq

Create project, first build (unsuccessful) and error:
https://pastebin.com/pNmM3eMM

**To Reproduce**
1. Fresh Install AndroidIDE 
2. Download openjdk etc. From App Website
3. Install them in AndroidIDE
4. After Install and restart - create new project, first build - result: error
5. Try [this to "solve"](https://github.com/itsaky/AndroidIDE/issues/28#issuecomment-1009748622) 
6. After update openjdk - edit ide-environment.properties (which is empty) as described
7. Create new project, build - error like above
8. Check ide-environment.properties - its still empty (expect the added Line from the link above)

**Expected behavior**
One compiled - even empty - project

**Screenshots**

**Details (please complete the following information):**
 - Device: Samsung A50 (A505FN)
 - OS: Android 11
 - AndroidIDE v2.0.0-beta

**Additional context**
It would really be useful to have a guide on what to do to make the application work properly. 
Im not trying to attack somehow - I like the application but I can not even use it without encountering some "critical" error - I have been trying to approach this application for several months and I always end up in the same place - on errors and without one app compiled.

**Comment by itsaky** [comment]
> After createing project, first build (unsuccesful), restart app, build once again just to get that: https://pastebin.com/Tv5NxFsq

This issue happens on some devices and can be solved by using JDK 17. But, as the build output says, you're using JDK 11 (`HOME/jdk`).

I think both of your issues can be solved with JDK 17. `JDK 11` seems to have issues with file locks.

**Comment by thewolfprod** [comment]
I installed the app again and tried again with this steps:
1. Open Terminal,
2. I checked the Java version `java -version` - It showed me that this is version 11
3. `pkg up` then `pkg in openjdk-17`
4. Then I edited `ide-environment.properties`
5. Checked one more time Java version - shows me Java 11 again
6. Restart app, Open Terminal, Check Java version again - now shows Java 17
7. Create App (Empty Template), First Build and unsuccessful because:
`
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed : android:exported needs to be explicitly specified for <activity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.
`
8. Added `android:exported="true"` to MainActivity
9. Compile Again - Success 😀

So I tested again - I created a new project but this time from an example with Navigation Drawer I got the same error with `android:exported`
$SYSROOT/etc/ide-environment.properties still contains only the line I added but if the applications build correctly, I guess that's how it's supposed to be

So - so far everything works - it is strange because in addition to checking the Java version I do the same steps as usual.
