### ISSUE TITLE
can't load the listview component

### ISSUE THREAD

**Issue by woshigenm** [itsaky/AndroidIDE#145]
I can't load the listview component

Exception:
java.lang.ClassNotFoundException: Didn't find class "com.itsaky.inflater.adapters.android.widget.ListViewAttrAdapter"

 - Device: vivo x60
 - OS: Android 11
 - AndroidIDE Version 2.0-beta

<img src="https://user-images.githubusercontent.com/99122353/160285357-6cdc4e18-6cb7-4ffe-899c-92f06bea71ef.jpg" width="350"/>

**Comment by itsaky** [comment]
There is no attribute adapter implementation for `ListView` at the moment. I'll add it soon.
