### ISSUE TITLE
Build Failed ( Daemon startup failed )

### ISSUE THREAD

**Issue by OshekharO** [itsaky/AndroidIDE#146]
Have tried building the apk in Android studio and it was successful but when I tried on this IDE it's showing build failed.

The app is developed using kotlin language.

Log: [https://nekobin.com/moroyisira](https://nekobin.com/moroyisira)

**Comment by MrIkso** [comment]
added `android.aapt2FromMavenOverride=/data/data/com.itsaky.androidide/files/framework/android-sdk/build-tools/31.0.0/aapt2` 
this line to gradle.properties

**Comment by itsaky** [comment]
Or you can use Android Gradle Plugin v7.0.2

**Comment by OshekharO** [comment]
From where can I get Android Gradle Plugin v7.0.2?
