### ISSUE TITLE
[FEATURE]: Godot - Bridge the gap

### ISSUE THREAD

**Issue by anonimo82** [itsaky/AndroidIDE#148]
**Is your feature request related to a problem? Please describe.**
It's now possible to create games with Godot inside Android, support APK exporting

**Describe the solution you'd like**
Use AndroidIDE's SDK to deploy APKs from Godot editor

**Describe alternatives you've considered**
None yet

**Additional context**
Since Godot editor now runs on Android (https://downloads.tuxfamily.org/godotengine/3.5/beta3/), and Android deployment needs a valid SDK, maybe you can consider supporting AndroidIDE (https://github.com/itsaky/AndroidIDE - https://androidide.com/) which provides a minimal Android SDK, to compile Android projects, inside Android!!! =)

Also see here (https://github.com/godotengine/godot-proposals/discussions/4324)

Cheers =)

**Comment by anonimo82** [comment]
P.S.: This would need the NDK support, is this possible?
This is NOT an April fool, despite the date. Try and see.

**Comment by itsaky** [comment]
> Since Godot editor now runs on Android (https://downloads.tuxfamily.org/godotengine/3.5/beta3/)

I tried it once. It works. But integrating something like that in AndroidIDE will be time consuming.
I might think of adding it in future ***stable*** versions. But for now, there are other important things in the IDE that needs attention.

> P.S.: This would need the NDK support, is this possible?

AndroidIDE does not have official NDK support yet. But there is [NDK port by Lzhiyong](https://github.com/Lzhiyong/termux-ndk) which you can setup in AndroidIDE.

**Comment by anonimo82** [comment]
No, I weren't referring to any integration, just to find a way to export a project from Godot and then build it with Android IDE.
Excuse me, maybe I've expressed myself bad.
Does the NDK support you mentioned work well?
Would you mind arranging with its developer to make it official, in such a situation?
Thanks for replying tough.

**Comment by itsaky** [comment]
> No, I weren't referring to any integration

Sorry. My bad. What's the issue with building the project?

> Does the NDK support you mentioned work well?

Yes. It works good (haven't tried `r24` port, but `r23b` works good).

> Would you mind arranging with its developer to make it official, in such a situation?

Currently, the NDK is not built for 32-bit Android devices. Also, it requires Android 9 or newer to work and AndroidIDE's minimum required API is `26` (Android 8, Oreo). This is from the README of `termux-ndk`: 
> I don't provide the linux and 32-bit versions, because there is not enough time to maintain and I have many other things to do, so you know!!

**Comment by anonimo82** [comment]
I got some build issues, but I don't remember now.
I'll try again later and report.
Well, I have a aarch64 with Android 10, so no problem.

**Comment by anonimo82** [comment]
P.S.: By the way, exporting Android Studio suitable code could require effort from both parties

**Comment by anonimo82** [comment]
No, I mean exporting from Godot.
We need a suitable source tree exported from Godot, and that such source will be built with Android IDE

**Comment by itsaky** [comment]
Yeah.

AndroidIDE fully supports Gradle projects. So, unless the project exported from Godot does not use Gradle build system, it shouldn't be a problem.

**Comment by anonimo82** [comment]
It does, and AFAIK it requires NDK.
Trying a build right now, I'll keep you posted

**Comment by anonimo82** [comment]
Here you are:
https://pastebin.com/JcTkd61a

**Comment by itsaky** [comment]
Okay.

There are some issues with the tooling API implementation in AndroidIDE. So, if your project is big enough, you might get an `OOM` error in the IDE. In that case, you could use the release version of AndroidIDE or [APK from this workflow](https://github.com/itsaky/AndroidIDE/actions/runs/2238915382).

**Comment by itsaky** [comment]
> Here you are:
https://pastebin.com/JcTkd61a

I'll look into it after some time.

**Comment by anonimo82** [comment]
Thanks so much, I hope we'll sort this out.
Also gonna ask on Discord

**Comment by anonimo82** [comment]
If you have time and will, here is the full project, as Godot generates it.
First thing is the main module is not named "app", then maybe NDK is needed (not sure)

Here it is (for 7 days) https://www.filemail.com/d/szttjwohqdhtajk

**Comment by anonimo82** [comment]
@itsaky so, can you help me?
At least, will you tell me what do I need to rename my main module to "app"?
Thanks =)

**Comment by itsaky** [comment]
Yeah. I tried to build the project in AndroidIDE. There were some modifications needed in the IDE to support Godot projects (bec2b6918dc86c97f682f6bc122a178045e046f8).

You can try out [this](https://github.com/itsaky/AndroidIDE/actions/runs/2362775099) build of AndroidIDE. However, it is unstable and currently being tested.

**Comment by itsaky** [comment]
> Here it is (for 7 days) https://www.filemail.com/d/szttjwohqdhtajk

I don't know why, but the generated APKs are not signed in this project (you could try altering the `signingConfigs`). Also, there is a bug with AAPT2 used in recent builds of AndroidIDE. See [this](bec2b6918dc86c97f682f6bc122a178045e046f8).

**Comment by anonimo82** [comment]
I didn't understand your message, and I'd prefer not to join Telegram groups, because every time I do, I receive spam and threatening messages from folks which wants my userid. Please, can you explain further?

**Comment by itsaky** [comment]
> Here it is (for 7 days) https://www.filemail.com/d/szttjwohqdhtajk

I had to modify the initialisation process in AndroidIDE to support these type of projects. You can try [this](https://github.com/itsaky/AndroidIDE/actions/runs/2362775099) build of AndroidIDE to build projects that are exported from Godot.

After building this project, the generated APKs are not signed. This might be due to wrong configuration in any of the build scripts. To fix this, you can configure `signingConfigs` in your project's `build.gradle` file and provide your own signing key to sign the projects.

The AAPT2 provided by AndroidIDE has a bug. It does not recognise resource files in some cases (see #193). I'm working on it and it'll be fixed soon.

**Comment by anonimo82** [comment]
I successfully built the project.
Where will the apk should be?

**Comment by itsaky** [comment]
The APK should be in the `build/outputs/apk/<variant>/` directory where `<variant>` is the build variant (debug, release, dev, etc).
<br>
> I successfully built the project.

If this issue is solved, consider closing the issue.

**Comment by anonimo82** [comment]
Yes, thanks a lot.
Just a last one, how can I manually sign an APK?

**Comment by itsaky** [comment]
If you want Gradle to sign the APKs, see [this](https://stackoverflow.com/a/21020469). If you want to sign the APKs yourself, see [this](https://stackoverflow.com/a/24833908).

**Comment by anonimo82** [comment]
Thanks so much!!!
I installed the APK.
Now, sound and input doesn't work, but I guess its Godot issue.

**Comment by itsaky** [comment]
Yeah. I installed the APK too and I wasn't able to do anything in the application.

**Comment by anonimo82** [comment]
Just curious, are you gonna include a keystore generator?

**Comment by itsaky** [comment]
Not so soon at least. You could use the `keytool` from JDK to generate keystores.

**Comment by anonimo82** [comment]
Ok, it's good

**Comment by anonimo82** [comment]
I forgot to ask: will the Android IDE you linked here be the next official one?

**Comment by anonimo82** [comment]
@itsaky ?

**Comment by itsaky** [comment]
Yes. With some improvements.

**Comment by anonimo82** [comment]
Thanks again
