### ISSUE TITLE
Popup menu is in wrong screen location

### ISSUE THREAD

**Issue by uzariustics123** [itsaky/AndroidIDE#159]
Whenever a highlighted text is in the lower part of the screen the popup menu/actions will also be at the lower screen eventhough there's already no enough space for it to be visible in the screen popup actions still shows up at bottom and and everytime I highlight a text again the popup menus becomes lower and lower

 - Device: [POCO X3]
 - OS: [e.g. Android 10]
 - AndroidIDE Version [Latest commit at 04/13/22]

**Comment by uzariustics123** [comment]
![Screenshot_2022-04-13-08-20-18-943_com itsaky androidide](https://user-images.githubusercontent.com/102352925/163075141-dfc096f0-7fb0-45c4-828e-a7b1b607e442.jpg)

**Comment by itsaky** [comment]
This has been fixed in the recent commits.
