### ISSUE TITLE
İ need help

### ISSUE THREAD

**Issue by WhiskyModz** [itsaky/AndroidIDE#167]
![Screenshot_2022-04-20-19-13-46-579_com itsaky androidide](https://user-images.githubusercontent.com/96978959/164279750-87500596-2932-4707-bd7c-199d415a7b22.jpg)
![Screenshot_2022-04-20-19-13-46-579_com itsaky androidide](https://user-images.githubusercontent.com/96978959/164279797-9ea95977-8f45-4bdb-9a85-306492310053.jpg)
]
 -

**Comment by itsaky** [comment]
You can try to use [termux-ndk](https://github.com/Lzhiyong/termux-ndk).
