### ISSUE TITLE
Layout Previewer caused Autocomplition issue

### ISSUE THREAD

**Issue by codejoker01** [itsaky/AndroidIDE#169]
After clicking on the layout previewer of a layout which have unsupported views, the autocomplition don't work.

**To Reproduce**

1. Create an XML layout file with unsupported widgets (views) (androidx or material)
2. Open the layout previewer
3. Get back to the editor
4. Check if the autocomplition works or not

_Screenshots_

![Screenshot_20220423-075956_AndroidIDE.jpg](https://user-images.githubusercontent.com/102878244/164878682-34a2fced-fe35-4532-b92b-df3b79ab8013.jpg)

![Screenshot_20220423-080031_AndroidIDE.jpg](https://user-images.githubusercontent.com/102878244/164878686-acc20481-9c9b-43fc-b146-095b4a067c58.jpg)

![Screenshot_20220423-080057_AndroidIDE.jpg](https://user-images.githubusercontent.com/102878244/164878692-cf5512fd-e63d-4a74-a82f-795499097408.jpg)

**Comment by itsaky** [comment]
Is there anything related to this in the IDE logs?

**Comment by codejoker01** [comment]
I haven't checked that, let me do it now.

**Comment by codejoker01** [comment]
I've tried to find something on the IDE logs, but there's nothing useful inside it.

Here is the log:

EditorActivity       I   Opening file at index:  0  file:   /storage/emulated/0/AndroidIDEProjects/Login/app/src/main/res/layout/fragment_login.xml 
EditorActivity       I   Launching UI Designer... 
DesignerActivity     D   Inflating layout file:  /storage/emulated/0/AndroidIDEProjects/Login/app/src/main/res/layout/fragment_login.xml 
DesignerActivity     D   Resource directories:  /storage/emulated/0/AndroidIDEProjects/Login/app/src/main/res 
FileTreeFragment     D   Restoring tree view state:  '3;2:3;1:2:3;4:1:2:3;1:4:1:2:3;2:1:4:1:2:3;2:2:1:4:1:2:3;5:1:2:3;3:5:1:2:3' 
DesignerActivity     D   onDestroy [com.itsaky.androidide.DesignerActivity]
