### ISSUE TITLE
Hello I Yours AndroidIDE User This 

### ISSUE THREAD

**Issue by azmatjan520** [itsaky/AndroidIDE#173]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Details (please complete the following information):**
![Screenshot_2022-04-25-01-31-29-10_9ad8e654efd333b66ab21513aa36e36c](https://user-images.githubusercontent.com/98287786/164989588-511b2cb1-d968-4dbe-aed7-6446a6c40838.png)
![Screenshot_2022-04-25-01-38-21-31_9ad8e654efd333b66ab21513aa36e36c](https://user-images.githubusercontent.com/98287786/164989602-befb6a22-42a6-4f79-a9db-196c4f5fe775.png)
![Screenshot_2022-04-25-01-38-57-19_9ad8e654efd333b66ab21513aa36e36c](https://user-images.githubusercontent.com/98287786/164989611-d6380eee-26ca-48a8-af09-62b598bdd0aa.png)
![Screenshot_2022-04-25-01-39-12-94_9ad8e654efd333b66ab21513aa36e36c](https://user-images.githubusercontent.com/98287786/164989617-35b48527-47a1-4a44-9c94-777b21fdc5d4.png)

 - Device: [e.g. OPPOA11]
 - OS: [e.g. Android 9]
 - AndroidIDE Version [e.g. v2.0.1-beta]

**Additional context**

**Comment by itsaky** [comment]
Could you explain what's the issue?
