### ISSUE TITLE
Keyboard Issues

### ISSUE THREAD

**Issue by dude-shah** [itsaky/AndroidIDE#185]
**Describe the bug**

When using **gboard** to type in **AndroidIDE** gesture typing don't work, suggestion strip don't show up, suggestions strip also contain clipboard etc which dont show up because of this bug, but other keyboards show suggestions and also do the geature typing
**To Reproduce**
Use Gboard in AndroidIDE.

**Expected behavior**

**Screenshots**

**Details (please complete the following information):**
 - Device: [e.g. realme 3 Pro] realme 6
 - OS: [e.g. Android 11] Android 11
 - AndroidIDE Version [e.g.  # v1.0.3-alpha] latest 2.0.1 beta

**Additional context**

**Comment by itsaky** [comment]
The suggestions from the keyboard are intentionally suppressed. However, you can disable this from IDE preferences.

**Comment by dude-shah** [comment]
> The suggestions from the keyboard are intentionally suppressed. However, you can disable this from IDE preferences.

Where exactly is this setting.. can you guide me

**Comment by itsaky** [comment]
Open AndroidIDE -> Go to 'Preferences' -> Editor -> Visible password flag.
