### ISSUE TITLE
Output result issue

### ISSUE THREAD

**Issue by dude-shah** [itsaky/AndroidIDE#186]
**Describe the bug**

I'm new in Java, so this might not be considered an issue but my inexperience.
I try to run simple program like Hello world but its not showing output, This code works perfectly in other IDE's (desktop once) and even in online ide for java but it's showing weird problem here.
Program
![Screenshot_2022-04-30-18-46-48-57_9ad8e654efd333b66ab21513aa36e36c.jpg](https://user-images.githubusercontent.com/63038690/166108110-0346b0b6-f5ea-44a9-9717-b72397ac6c77.jpg)
Issues it's showing .. 
![Screenshot_2022-04-30-18-39-32-43_9ad8e654efd333b66ab21513aa36e36c.jpg](https://user-images.githubusercontent.com/63038690/166107958-62c20d3c-be02-49aa-8ae1-cf9f32c5e647.jpg)

**Details (please complete the following information):**
 - Device: realme 6
 - OS: Android 11
 - AndroidIDE Version 2.0.1 beta

**Comment by itsaky** [comment]
AndroidIDE, as the name suggests, is made to build Android applications, not Java console applications.
