### ISSUE TITLE
[Feature request] - LibGDX Template/Project generator

### ISSUE THREAD

**Issue by anonimo82** [itsaky/AndroidIDE#20]
Hello everyone.
  I'd like to see, in this IDE, a LibGDX Project generator similar to the "official" one: http://libgdx.com/dev/project-generation/ and maybe support gdx-gltf too: https://github.com/mgsx-dev/gdx-gltf

Thanks in advance for anything.

**Comment by itsaky** [comment]
This is already planned for next release. See #14.

**Comment by anonimo82** [comment]
I'm very sorry for this inconvenience, I should did a search before posting. My apologies
