### ISSUE TITLE
[FEATURE]: Add new version of aapt2:7.2.1

### ISSUE THREAD

**Issue by ask9027** [itsaky/AndroidIDE#200]
I import a android studio latest project to android ide,
At the time of build i getting a AAPT2:7.2.1 deomen error.
Please fix this problem, or release new version of aapt2:7.2.1, Thanks

**Comment by ask9027** [comment]
Opps i forget to add title..

**Comment by itsaky** [comment]
The AAPT2 that AndroidIDE uses currently, is compatible with Android Gradle Plugin. You can specify `android.aapt2FromMavenOverride` in `gradle.properties` file to override the aapt2 executable that AGP uses.

Alternatively, you could use APK from GitHub actions. Those versions of AndroidIDE automatically specify this property for you.

**Comment by itsaky** [comment]
AndroidIDE now uses the latest build of `aapt2`.
