### ISSUE TITLE
ERROR: JAVA_HOME is set to an invalid directory

### ISSUE THREAD

**Issue by 15970915309** [itsaky/AndroidIDE#201]
`ERROR: JAVA_HOME is set to an invalid directory: ROOT/framework/jdk Please set the JAVA_HOME variable in your environment to match the location of your Java installation.`

**Comment by itsaky** [comment]
Have you installed JDK? If not, you can either install JDK 11 or JDK 17. Use of JDK 17 is always recommended.

If you install JDK 17, you'll have to edit `$SYSROOT/etc/ide-environment.properties` file and point `JAVA_HOME` to `$SYSROOT/opt/openjdk`. For example, the file should contain :

`JAVA_HOME=$SYSROOT/opt/openjdk`.
