### ISSUE TITLE
The default build cannot pass after a new project is created

### ISSUE THREAD

**Issue by ZeroAicy** [itsaky/AndroidIDE#202]
**Describe the bug**

The default build compilation fails after a new project is created, but it can be compiled by using'bash gradlew build'in the terminal. Then compile successfully using the default build.

**To Reproduce**

Create a new project, wait for compilation, and then compilation fails
**Expected behavior**

I don't know if the build of the run button is different from the terminal command. The two results should be consistent.
**Screenshots**

![S20603-09584922](https://user-images.githubusercontent.com/83522578/171772302-0cde49d6-0361-49b4-a2ba-c37b252d199b.png)

**Details (please complete the following information):**
 - Device: [e.g. meizu16s  Pro]
 - OS: [e.g. Android 10]
 - AndroidIDE Version [e.g. v2.0.1-beta]

**Additional context**

**Comment by MrIkso** [comment]
Not actually in latest version from GitHub Actions

**Comment by itsaky** [comment]
These are compilation errors in your project. Fix those errors.

This is not anyhow related with AndroidIDE. If you think this is a mistake, feel free to reopen this issue.
