### ISSUE TITLE
[FEATURE]: 

### ISSUE THREAD

**Issue by azmatjan520** [itsaky/AndroidIDE#203]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [Send the new version of androidIDE software quickly. I look at your official website every day, but the new version does not come out....]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by itsaky** [comment]
Next release will not be available until we properly test the newly implemented Gradle Tooling API. Progress update is provided in the Telegram group.

And please fill all the sections of the feature/bug report issue templates. If this is not possible, remove those sections.
