### ISSUE TITLE
Vertical Actions Menu in Editor

### ISSUE THREAD

**Issue by BanDroid** [itsaky/AndroidIDE#207]
The vertical actions menu was *again* having problems with the position and size.

This one is blocking the cursor when the keyboard is shown.

![Screenshot_2022-06-04-20-17-59-876_com itsaky androidide](https://user-images.githubusercontent.com/68449470/172018587-ec2138a3-2e57-40fa-afcd-ae33d00ad97e.jpg)

**Comment by MatheusTGamerPro** [comment]
@itsaky in the latest builds it was added, I think you can now mark this Issue as resolved.

**Comment by itsaky** [comment]
Yeah.

@MatheusTGamerPro Thanks.
