### ISSUE TITLE
[FEATURE]: Add support for AGP 7.2.1

### ISSUE THREAD

**Issue by KanhaKanhaiya** [itsaky/AndroidIDE#210]
**Is your feature request related to a problem? Please describe.**
Yes. AndroidIDE gives me error on increasing the minor version from 7.2.0 to 7.2.1.

**Describe the solution you'd like**
Please add support for the version 7.2.1.

**Describe alternatives you've considered**
No alternatives. AndroidIDE is one of its kind.

**Additional context**
https://developer.android.com/studio/releases/gradle-plugin#7-2-0

###### To see the other bug fixes included in this release, see the [Android Studio Chipmunk Patch 1 release notes](https://developer.android.com/studio/releases#patch-releases).

Please update the supported version to 7.2.1. 
I am using the Latest GitHub Actions version of AndroidIDE.

**Comment by itsaky** [comment]
Yes, AndroidIDE is currently restricted to a fixed Android Gradle Plugin version.

But I'm working on making it compatible with other newer/older versions too. It'll be available soon.

**Comment by KanhaKanhaiya** [comment]
:+1:

**Comment by ask9027** [comment]
Use this to fix aapt2
https://github.com/Lzhiyong/termux-ndk/issues/106#issuecomment-1133898302

**Comment by itsaky** [comment]
> Use this to fix aapt2
https://github.com/Lzhiyong/termux-ndk/issues/106#issuecomment-1133898302

That is irrelevant to this topic.

And we do not use that method anymore. Instead `android.aapt2FromMavenOverride` property is used.

**Comment by ask9027** [comment]
Your choice

**Comment by KanhaKanhaiya** [comment]
Feature implemented in https://github.com/itsaky/AndroidIDE/commit/c8bdc40e6f9a5d57099e16e01d93dd5ad6168e4a
