### ISSUE TITLE
[FEATURE]: Automatic file saving

### ISSUE THREAD

**Issue by rdm600** [itsaky/AndroidIDE#217]
Please make a normal saving files. Before starting to compile, I have to press "Save" to get changes accepted. This is very inconvenient. It would also be possible to make autosave setting and choose interval there (5 seconds, 15 seconds, 30 seconds, 45 seconds, a minute)

**Comment by itsaky** [comment]
There already a PR opened with support for saving files before executing any task. See [this](https://github.com/itsaky/AndroidIDE/pull/209/commits/134d07873a774584224df6dd0c84415b5cb72355).

We might consider adding support for saving of files in stable releases. Not before that.
