### ISSUE TITLE
Wrong code highlight and tip

### ISSUE THREAD

**Issue by SeeYoung233** [itsaky/AndroidIDE#22]
I get the wrong code highlight,and there isn't code tip.
Highlight: @Override
Tip: ct
After i type c or ct ,there is nothing happened.
![Screenshot_20211112-213615_AndroidIDE](https://user-images.githubusercontent.com/30569626/141476242-1a12ead4-c846-4166-ad35-75c5b30a8c8b.png)

**Comment by itsaky** [comment]
@SeeYoung233 Could you check if this issue still? Use any of the APKs from GitHub actions.
