### ISSUE TITLE
Broken import autocomplete items

### ISSUE THREAD

**Issue by MrIkso** [itsaky/AndroidIDE#225]
**Describe the bug**
When typing `import package_name` show incorrect subpackages and classes names. Names trimmed..

**Screenshots**
![Screenshot_20220624-024929_AndroidIDE](https://user-images.githubusercontent.com/43380144/175433074-e8bd46f1-d8ff-4663-919c-fdd60a9e94b6.jpg)

**Comment by itsaky** [comment]
Fixed.
