### ISSUE TITLE
armv7a (arm32) support?

### ISSUE THREAD

**Issue by masterjavaofficial** [itsaky/AndroidIDE#23]
Why don't you guys build it supporting arm32 archs? Mine device is arm32, and I've to use Termux (its openjdk-17, gradle packages) and Build-Tools (like aapt2) from https://github.com/Lzhiyong/sdk-tools, and the code editor is Acode. Its very hard to build apps like this. If you had built the IDE for arm32 also, it would be very helpful for me.

**Comment by itsaky** [comment]
Support for armv7a devices is planned. The SDK tools have been successfully built for 32-bit devices. I have to build JDK for 32-bit devices.

However, due to this, the next release will be delayed.

**Comment by masterjavaofficial** [comment]
> I'm so sorry for the late reply.
> 
> Support for armv7a devices is planned. The SDK tools have been successfully built for 32-bit devices. I have to build JDK for 32-bit devices.
> 
> However, due to this, the next release will be delayed.

Ahh, can't wait more! It will be the Android Studio running on Android!

However, thanks for the reply and letting me know.

**Comment by masterjavaofficial** [comment]
@itsaky any progress update?

**Comment by itsaky** [comment]
Yeah. All of the build tools have been built successfully for 32-bit devices (except for cmake in Android SDK).

32-bit support will be available in first beta release.

**Comment by masterjavaofficial** [comment]
> Yeah. All of the build tools have been built successfully for 32-bit devices (except for cmake in Android SDK).
> 
> 32-bit support will be available in first beta release.

Nice to learn. Btw, is cmake in Android SDK? Should it be in Android NDK? And when you're releasing the first beta?

**Comment by itsaky** [comment]
Oh. Sorry. That was a mistake.

We don't currently have a fixed date for the release of first beta. It'll take some time. Main features that are planned for the release:
- UI Designer (at least something to preview the XML layout)
- 32-bit support
- Git support (at least in terminal)

But I'll try to release it as soon as possible.

**Comment by masterjavaofficial** [comment]
Any date fixed for the next update with armv7a support?

**Comment by itsaky** [comment]
It would take some time. It's not only about 32-bit support, I have to implement a lot more in the IDE.

**Comment by masterjavaofficial** [comment]
> It would take some time. It's not only about 32-bit support, I have to implement a lot more in the IDE.

Yeah I know you'd improve it in more ways. I just asked about the update that would contain 32 bit support.

**Comment by masterjavaofficial** [comment]
@itsaky I'm back after hard studying for a month, and I'm surprided to see that you released an update with support for 32 bit, many more improvements and making the project open-source!! You're much appreciated!! Keep going! 👏👏

**Comment by masterjavaofficial** [comment]
@itsaky after I download the apk from androidide.com, I can't still install it on my 32 bit device! It says the app was not installed! Why!?

**Comment by itsaky** [comment]
Try using the APK from GitHub actions. See [this video](https://t.me/androidide_discussions/16610) for installation instructions.

You'll have to uninstall the website version. Because website version and GitHub actions version has different signing key.
