### ISSUE TITLE
Improve data shown in completion list item

### ISSUE THREAD

**Issue by QiubyZ** [itsaky/AndroidIDE#241]
Change the Method explanation, to Return value.
example

[ M ] xxx.toString [String]

And give the background color of the symbols of class, method and other, I hope all the symbol background colors are not the same and more variety

![IMG_20220629_025957](https://user-images.githubusercontent.com/41333888/176261428-9f667f58-1a1e-47ef-a96c-1fd0b5491340.jpg)

**Comment by itsaky** [comment]
Added in 0e4bc2a12133a6536813751daea195657dcd5214.
