### ISSUE TITLE
Automatically create layout file when creating activity classes

### ISSUE THREAD

**Issue by QiubyZ** [itsaky/AndroidIDE#244]
Added Automation of xml file creation, when creating Activity Class.
![Tak berjudul9_20220629040131](https://user-images.githubusercontent.com/41333888/176274631-55c117f1-38b7-40b1-beb3-145aab024e6d.png)

**Comment by MatheusTGamerPro** [comment]
@itsaky now this Issue can be closed

**Comment by itsaky** [comment]
Added in #365.
