### ISSUE TITLE
When using ViewPager coin, the software made by  quits.

### ISSUE THREAD

**Issue by azmatjan520** [itsaky/AndroidIDE#246]
When using ViewPager coin, the software made by  quits.

**Comment by MrIkso** [comment]
Write normally description on issue

**Comment by itsaky** [comment]
This does not follow the [contribution guidelines](https://github.com/itsaky/AndroidIDE/blob/main/CONTRIBUTING.md).

**Comment by datechies** [comment]
@itsaky hi
