### ISSUE TITLE
WebSite poor usability

### ISSUE THREAD

**Issue by anonimo82** [itsaky/AndroidIDE#254]
Hello everyone.
When trying to select text to download the build tools installer, I get the option to select the URL for the APK - not very convenient.
I'd rather have the ability to select text, copy it then paste in the AndroidIDE terminal for execution.
This is the same even with an MHL cable, can't select any text.
I'm also facing problems using AndroidIDE with a MHL cable and USB Keyboard/Mouse, the terminal won't collect my input - neither from my USB devices, neither from my OnScreen inputs.

Please, fix this =)

**Comment by itsaky** [comment]
The terminal, in fact the whole IDE is currently not optimized for physical keyboard/mouse. For the on screen input issue, provide a way to reproduce the issue.
Instructions for installing build tools is also available at [androidide-build-tools.](https://github.com/itsaky/androidide-build-tools).

**Comment by anonimo82** [comment]
Here you are:
just go to androidide.com and try to select some text

**Comment by itsaky** [comment]
@MarvinStelter Please look into the website issue.

**Comment by anonimo82** [comment]
Should we close this?

**Comment by MarvinStelter** [comment]
I'll fix it now

**Comment by MarvinStelter** [comment]
Fixed!
