### ISSUE TITLE
ReadMe.md - Updated?

### ISSUE THREAD

**Issue by anonimo82** [itsaky/AndroidIDE#259]
Hello everyone.
I lurk every now and then in the ReadMe.md to see if are there any updates to the IDE itself, but even if I see updates to the repository, I can't see any progress logged in the ReadMe.md.
Is this a fault in the logging system (eg, are the updates not being logged in the ReadMe), or is it still stuck to that old situation?

Thanks for any help.

**Comment by itsaky** [comment]
README is updated for important changes only (for example, the installation method for AndroidIDE was changed so the README was updated).

All other changes are logged into a file in the `changelog` directory. However, these files are not updated daily but only after a number of finalized changes.

**Comment by anonimo82** [comment]
Ok, thanks.
I just wonder those checkboxes, what's done and what's not

**Comment by itsaky** [comment]
Well, all those checkboxes are correctly marked. We could a few more checkboxes about the things that are planned or already completed. I'll update it later.

**Comment by anonimo82** [comment]
I see the checkboxes are more or less the same.
Has this been worked out?
