### ISSUE TITLE
[BUG] Gradle just doesn't work

### ISSUE THREAD

**Issue by Hakalle** [itsaky/AndroidIDE#268]
I installed all the tools (including `cmake`) in AndroidIDE before creating any project (no matter if I installed it or not, unfortunately it is still the same), I am running Android 12.1 (SDK 32, or: Android 12L), I created a new (random) project to test it, and as a result: It doesn't work.

I reinstalled twice (using the latest beta release) and it still doesn't work, see the logs (which I can share, build log shows nothing):
`GradleBuildService        I   Showing notification to user... 
EditorActivity            I   Gradle build service has been started... 
FileTreeFragment          E   Unable to restore tree state  treeState=null  treeView=com.unnamed.b.atv.view.AndroidTreeView@d8876b 
FileTreeFragment          E   Unable to restore tree state  treeState=null  treeView=com.unnamed.b.atv.view.AndroidTreeView@d8876b 
GradleBuildService        I   Starting tooling API server... 
CachingProject            D   Empty module data returned by tooling server. Ignoring... 
GenericEndpoint           W   Unsupported notification method: client/logMessage 
GenericEndpoint           W   Unsupported notification method: client/logMessage 
GradleBuildService        E   An error occurred while waiting for tooling API server to terminate 
GradleBuildService        E  java.lang.AbstractMethodError: abstract method "com.google.gson.TypeAdapter com.google.gson.TypeAdapterFactory.create(com.google.gson.Gson, com.google.gson.reflect.TypeToken)"
GradleBuildService        E  	at com.google.gson.internal.bind.JsonAdapterAnnotationTypeAdapterFactory.getTypeAdapter(JsonAdapterAnnotationTypeAdapterFactory.java:7)
GradleBuildService        E  	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:32)
GradleBuildService        E  	at com.google.gson.Gson.getAdapter(Gson.java:9)
GradleBuildService        E  	at com.google.gson.Gson.fromJson(Gson.java:5)
GradleBuildService        E  	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.read(MessageTypeAdapter.java:8)
GradleBuildService        E  	at com.google.gson.Gson.fromJson(Gson.java:6)
GradleBuildService        E  	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.parseMessage(MessageJsonHandler.java:3)
GradleBuildService        E  	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:6)
GradleBuildService        E  	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:12)
GradleBuildService        E  	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:3)
GradleBuildService        E  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
GradleBuildService        E  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
GradleBuildService        E  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
GradleBuildService        E  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
GradleBuildService        E   Caused by: java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: abstract method "com.google.gson.TypeAdapter com.google.gson.TypeAdapterFactory.create(com.google.gson.Gson, com.google.gson.reflect.TypeToken)"
GradleBuildService        E  	at java.util.concurrent.FutureTask.report(FutureTask.java:123)
GradleBuildService        E  	at java.util.concurrent.FutureTask.get(FutureTask.java:193)
GradleBuildService        E  	at com.itsaky.androidide.services.GradleBuildService$ToolingServerRunner.run(GradleBuildService.java:39)
GradleBuildService        E  	at java.lang.Thread.run(Thread.java:920)
GradleBuildService        E  
GradleBuildService        E  
EditorActivity            I   Opening file at index:  0  file:   /storage/emulated/0/AndroidIDEProjects/MyApplication(1)/gradle.properties 
FileTreeFragment          E   Unable to restore tree state  treeState=  treeView=com.unnamed.b.atv.view.AndroidTreeView@14740b3 
FileTreeFragment          E   Unable to restore tree state  treeState=  treeView=com.unnamed.b.atv.view.AndroidTreeView@8db8274 
FileTreeFragment          E   Unable to restore tree state  treeState=  treeView=com.unnamed.b.atv.view.AndroidTreeView@31b567f 
FileTreeFragment          E   Unable to restore tree state  treeState=  treeView=com.unnamed.b.atv.view.AndroidTreeView@517d13e`

The notification just pops up and does nothing infinitely. (PS: My device have 64-bit support)

**Comment by itsaky** [comment]
This is a known error and was fixed in v2.1.1-beta.

**Comment by Hakalle** [comment]
Oh sorry! How embarrassing.

I didn't see version 2.1.1, I had read 2.1.0, I apologize for what happened.
