### ISSUE TITLE
Code formatting, optimize it

### ISSUE THREAD

**Issue by chengzhuangjie** [itsaky/AndroidIDE#278]

**Comment by BanDroid** [comment]
Please put right description of what you want to create of an issue with!!! Especially the problem you're experiencing of!

**Comment by itsaky** [comment]
Follow the [contribution guidelines](https://github.com/itsaky/AndroidIDE/blob/main/CONTRIBUTING.md) when opening issues.

AndroidIDE currently uses `google-java-format` to format java source code. It provides two code styles :
- `AOSP` : Uses 4-space soft tab indentation
- `Google`: Uses 2-space soft tab indentation

You can change the code style in IDE preferences.

**Comment by chengzhuangjie** [comment]
It should format the code like Android studio
