### ISSUE TITLE
自动补全无法提示R.id.xxx

### ISSUE THREAD

**Issue by 3091977221** [itsaky/AndroidIDE#281]
![Screenshot_20220713_200015_com.itsaky.androidide.jpg](https://user-images.githubusercontent.com/73690771/178728712-25b95b32-75a6-4b23-8205-0c899eedde6b.jpg)

这里的temux_tools我在xml添加了的

**Comment by AndreyKozhev** [comment]
Please write the titles and text of the issue/PR in English.
