### ISSUE TITLE
Can't access $PREFIX/etc/apt/sources.list

### ISSUE THREAD

**Issue by BasicGearwheel** [itsaky/AndroidIDE#288]
https://user-images.githubusercontent.com/61679493/179146497-6cbd93cb-9d5f-487c-b207-5e8fac4d7b14.mp4

Android 12 Origin OS
Other than that I can't change the source

**Comment by itsaky** [comment]
1. You tried to access the file from the Termux's data directory. Which is obviously not possible without root.

2. There is no `PREFIX` environment variable in AndroidIDE. Equivalent is `SYSROOT`. However, you could define your own variables for the terminal in the `~/.bashrc` file. If you want to define global environment variables (applicable for terminal as well as other things in the IDE), you define it in the `$SYSROOT/etc/ide-environment.properties` file (use `ideenv -e` command to edit).

**Comment by itsaky** [comment]
Another thing :
Termux packages cannot be used in AndroidIDE for obvious reasons. So selecting any of the Termux package mirrors with `termux-change-repo` (or anything else) won't work.

**Comment by BasicGearwheel** [comment]
But some people seem to be able to change mirror sites through the steps of Termux.

**Comment by itsaky** [comment]
Even if you manually change the mirror sites, the downloaded packages will not work. This is because Termux's data directory path is hardcoded in those packages.

**Comment by BasicGearwheel** [comment]
If this is the case, then I need to use a VPN to install development environments such as JDK, which will be a very long process.

**Comment by BanDroid** [comment]
> If this is the case, then I need to use a VPN to install development environments such as JDK, which will be a very long process.

For what? AndroidIDE already provide jdk 11 and 17, why would you want to change with such long and hard process?

**Comment by BasicGearwheel** [comment]
Emm, it's necessary to download.Right?
![Screenshot_2022_0715_134845](https://user-images.githubusercontent.com/61679493/179159492-f84a913c-f947-44f5-94d8-ec84dc316b38.png)

**Comment by BanDroid** [comment]
Have you follow the setup/installation guide? If yes, then that bug in your image is just LSP problem, yes we already recognize about this bug that is why @itsaky and some people trying to contribute on those changes for fixing LSP problem, but installing jdk from other repo is unnecessary, AndroidIDE provide jdk 11 or 17 in the setup

**Comment by BasicGearwheel** [comment]
https://user-images.githubusercontent.com/61679493/179161393-88def34a-826c-4851-83c7-14231b67f396.mp4

Sorry for not making it clear.If I don't use the VPN, there will be some problems installing Android SDK.

**Comment by BanDroid** [comment]
Oh i understood, have you try to use mobile data instead of wifi? I believe termux has that problem when someone trying to install packages but have problem connecting to the repo

**Comment by BasicGearwheel** [comment]
I tried just now.It's also like this.
