### ISSUE TITLE
Icon should indicate that lint is disabled

### ISSUE THREAD

**Issue by MarvinStelter** [itsaky/AndroidIDE#3]
When turning off lint it doest change his icon, it's not directly obvious if it's turned on or not

![Screenshot_2021-07-30-21-18-37-003_com.itsaky.androidide.jpg](https://user-images.githubusercontent.com/41212885/127701674-513a1852-3ec4-45e6-9d65-1793eb3ffe76.jpg)

**Comment by itsaky** [comment]
Fixed in v1.0.2-alpha. Icons of menu items are now disabled too.
