### ISSUE TITLE
Bug Gradle wrapper missing

### ISSUE THREAD

**Issue by ns8147732** [itsaky/AndroidIDE#30]

**Comment by ns8147732** [comment]
Gradle wrapper missing

**Comment by itsaky** [comment]
AndroidIDE automatically extracts gradle wrapper if it isn't already present. Please recheck.

**Comment by Etanarvazac** [comment]
I provided latest version (7.3.3) and IDE forces download of 7.1.1. Then it gets stuck on this error:
```
ERROR: could not disable heap pointer tagging, Operation not supported on transport endpoint
```
Gradle failed on first build in 2 ways...

**Comment by itsaky** [comment]
@Etanarvazac Your issue is totally unrelated to this. Please open a new issue (if it hasn't been opened already).

**Comment by itsaky** [comment]
An issue exists. See #28.

**Comment by itsaky** [comment]
Closing because of no response from author.
