### ISSUE TITLE
Images open in the editor as text

### ISSUE THREAD

**Issue by AndreyKozhev** [itsaky/AndroidIDE#316]
If you click on an image file in a project, for example, on a mipmap resource, it opens in the editor as text.
It is necessary to add an image viewer in the IDE, or at least the ability to view in a third-party program.
# Screenshots
![IMG](https://user-images.githubusercontent.com/103951737/179358352-0912a8c2-b675-4378-86d6-043fc2ed17cc.jpg)

**Comment by MrIkso** [comment]
It's issues related to this #177

**Comment by AndreyKozhev** [comment]
Okay
