### ISSUE TITLE
Suggest button fails.

### ISSUE THREAD

**Issue by Etanarvazac** [itsaky/AndroidIDE#35]
**Describe the bug**
Suggest button fails. Only subject and message is filled out.

**To Reproduce**
Literally tap on "Suggest" and the app asks where to send the message text only

**Expected behavior**
Upon opening the email application, user should have developer email pre-filled.

**Screenshots**

**Details (please complete the following information):**
 - Device: Samsung Galaxy S21 5G
 - OS: Android 12
 - (UI Designer 2.0.0-beta)

**Additional context**
N/A

**Comment by itsaky** [comment]
> Details (please complete the following information):

> - Device: Samsung Galaxy S21 5G
> - OS: Android 12
> - (UI Designer 2.0.0-beta)

You're talking about UI Designer here, I'm sorry it's not related to this repo.
