### ISSUE TITLE
Black EditText in new Material Design

### ISSUE THREAD

**Issue by MatheusTGamerPro** [itsaky/AndroidIDE#355]
after you add the new material design, there is a confusion in the EditText coloring, see in the video below:

https://user-images.githubusercontent.com/89700288/183772380-0a221299-c216-4e79-b127-3bdda86ecd29.mp4

When the editText's onFocus event fires, it changes color.

This is happening in the latest build on GitHub. (GitHub Actions)

**Comment by itsaky** [comment]
The migration isn't complete yet. I'll fix it today.

**Comment by itsaky** [comment]
Fixed in fdd5947e84d0ab9052d9e862ca45d343a8fa1911.
