### ISSUE TITLE
Notification bar color theme hides text

### ISSUE THREAD

**Issue by Etanarvazac** [itsaky/AndroidIDE#36]
**Describe the bug**
- Light theme turns bar black, text is also black
- Dark theme turns bar white, text is also white

**To Reproduce**
Simply toggle between themes and look at the notification bar.

**Expected behavior**
The text should be opposite of the bar color (black bar, white text (and vice versa))

**Screenshots**
White on white:
![SmartSelect_20220102-003123_UI Designer.jpg](https://user-images.githubusercontent.com/55290878/147867490-3e45db3c-2a43-426d-b6b7-e239e5970e95.jpg)
Black on black:
![SmartSelect_20220102-005300_UI Designer.jpg](https://user-images.githubusercontent.com/55290878/147867516-9c48ae36-1717-4e58-b957-d5220ca28a9f.jpg)

**Details (please complete the following information):**
 - Device: Samsung Galaxy S21 5G
 - OS: Android 12
 - (UI Designer 2.0.0-beta)

**Additional context**
N/A

**Comment by itsaky** [comment]
Looks like you misunderstood. That UI Designer is totally different from AndroidIDE. I stopped working on that UI Designer.

**Comment by Etanarvazac** [comment]
RIP....
