### ISSUE TITLE
[BUG] Layout Preview showing error codes 

### ISSUE THREAD

**Issue by Premjit-Chowdhury** [itsaky/AndroidIDE#37]
**Describe the bug**
When i try click Layout preview from my activity_main.xml which has Constraint Layout, RecyclerView, Material Fab button it gives me error in the layout preview page.

**Screenshots**
![Screenshot_2022-01-02-11-57-34-837_com itsaky androidide](https://user-images.githubusercontent.com/72644801/147868104-680530c5-e740-458b-a503-c1a13131b0e7.jpg)
![IMG_20220102_110845](https://user-images.githubusercontent.com/72644801/147868127-0fefcbfd-3a13-4ab1-95db-41a6b95f54ae.jpg)

**Comment by Premjit-Chowdhury** [comment]
And when back gesture/ back button pressed it is not going to xml screen instead showing this 
![Screenshot_2022-01-02-12-07-47-483_com itsaky androidide](https://user-images.githubusercontent.com/72644801/147868342-8730b6f6-aec5-4496-b774-d2cbd6c80bc6.jpg)

**Comment by itsaky** [comment]
This has been temporarily fixed. I'll implement the resource finder later.

**Comment by Premjit-Chowdhury** [comment]
![Screenshot_2022-01-08-11-18-25-665_com itsaky androidide]
(https://user-images.githubusercontent.com/72644801/148633220-d9f69e71-38ee-47a8-af28-bc9a9485dae2.jpg)

After returning from this screen it removes some xml codes.
![Screenshot_2022-01-08-11-18-20-660_com itsaky androidide](https://user-images.githubusercontent.com/72644801/148633227-ad9a727d-2530-42a4-929a-9ffd0a513d9d.jpg)
![Screenshot_2022-01-08-11-18-01-630_com itsaky androidide](https://user-images.githubusercontent.com/72644801/148633231-84b5047c-b940-4bbb-bb58-8b2139d99d8c.jpg)

++  Layout preview screen also not showing Constraint Layout

**Comment by Premjit-Chowdhury** [comment]
After creating new xml files they don't have this xml header
<?xml version="1.0" encoding="utf-8"?>

**Comment by itsaky** [comment]
> After returning from this screen 👆 it removes some xml codes
> After creating new xml files they don't have this xml header

Both should have been fixed now.

**Comment by Premjit-Chowdhury** [comment]
**Layout Preview auto deleting codes and  preview errors are fixed but after returning from this screen it auto remove xml header** 👇

![IMG_20220108_165344](https://user-images.githubusercontent.com/72644801/148666205-bd8c41bd-f3cb-4b91-8ce4-c67422e1dec9.jpg)
![Screenshot_2022-01-08-16-48-57-234_com itsaky androidide](https://user-images.githubusercontent.com/72644801/148666208-b555afd9-cc08-40c2-b341-821ee928cc14.jpg)

**AND when creating new xml files it sometimes by default have layout widget and Sometimes full blank** 👇
![Screenshot_2022-01-08-16-50-16-698_com itsaky androidide](https://user-images.githubusercontent.com/72644801/148666327-5e9f1f8f-c6d1-4692-847b-4ddae6156e86.jpg)

**Comment by itsaky** [comment]
In your screenshots, I did not see any missing code. The layout was not formatted and the order of child views was changed which I will of course fix.

And consider opening new issues

**Comment by Premjit-Chowdhury** [comment]
> In your screenshots, I did not see any missing code. The layout was not formatted and the order of child views was changed which I will of course fix.
> 
> And consider opening new issues for other problems

Ok

**Comment by itsaky** [comment]
Fixed. The UI Designer is now able to read values from resources.
