### ISSUE TITLE
Terminal emulator

### ISSUE THREAD

**Issue by harsh7i** [itsaky/AndroidIDE#373]
* Someone help me to use Termux in my android project !

I have an android project , i need to use termux as a code compiler, how can i implement termux and use in my android project ??

**Comment by deepkrg17** [comment]
What's this nonsense!
Describe the issue/suggestion/request briefly when opening issues.
And these types of questions must be asked in GitHub Discussions or Telegram.

**Comment by harsh7i** [comment]
> What's this nonsense! Describe the issue/suggestion/request briefly when opening issues. And these types of questions must be asked in GitHub Discussions or Telegram.

Sir I have tried many times but no one replies me what can i do sir ??

**Comment by itsaky** [comment]
@deepkrg17 Follow the code conduct. You could say he same politely. This behaviour will be tolerated!

**Comment by itsaky** [comment]
@harsh7i How is your issue related with AndroidIDE? You don't even explain the issue properly.

**Comment by BanDroid** [comment]
You should open this issue in termux repository

**Comment by harsh7i** [comment]
> You should open this issue in termux repository

Sir @itsaky
You used this properly , I think no one knows more about it than you. That's why i asked you for help.

**Comment by itsaky** [comment]
You didn't explain the issue to us. This repository is for AndroidIDE but I don't see your issue relatable.

You should probably open a discussion on GitHub or Telegram first.
