### ISSUE TITLE
[Bug]: Problems with Extra Keys in the editor

### ISSUE THREAD

**Issue by AndreyKozhev** [itsaky/AndroidIDE#381]
### What happened?

Some keys are not displayed, although they can be pressed, see the video below.

https://user-images.githubusercontent.com/103951737/184656734-37e201f3-af9a-46f4-a5db-cb12d77db13d.mp4

### What's the expected behavior?

All keys will be displayed.

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Relevant log output

```shell
No output.
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
Fixed in 0da4e2629cc81478f3ff0e68a2627977ddc5f3ce.
