### ISSUE TITLE
Keep showing Icon Preview Layout

### ISSUE THREAD

**Issue by QiubyZ** [itsaky/AndroidIDE#391]
Keep showing Icon Preview Layout although I open the keyboard.
Because it's really weird when I have to see the whole code while I can see it full when I open the keyboard.

https://user-images.githubusercontent.com/41333888/185482897-d8339915-99b9-4c17-8ae0-727669af6de2.mp4

**Comment by itsaky** [comment]
This is expected. When the keyboard is open, the `Undo` and `Redo` actions are given priority over all other actions. The `Run` button is supposed to be always visible. Due to this, there is no room for `Preview layout` action.

I don't think this needs to be fixed.

**Comment by QiubyZ** [comment]
> ini diharapkan. Saat keyboard terbuka, tindakan `Undo`dan `Redo`diberi prioritas di atas semua tindakan lainnya. Tombolnya `Run`seharusnya selalu terlihat. Karena ini, tidak ada ruang untuk `Preview layout`bertindak.
> 
> Saya rasa ini tidak perlu diperbaiki.

untuk apa tombol run selalu terlihat ? ini di Layout XML , coba perhatikan untuk apa Tombol Preview Layout dalam XML.

**Comment by QiubyZ** [comment]
> This is expected. When the keyboard is open, the `Undo` and `Redo` actions are given priority over all other actions. The `Run` button is supposed to be always visible. Due to this, there is no room for `Preview layout` action.
> 
> I don't think this needs to be fixed.


It's a matter of efficiency not about the tricks you build.

this is in Layout XML , try to see what the "Preview Layout" Button is for if in fact it's just because of an undo/redo problem it has to be hidden or Hide Keyboard to be visible. just return the Preview Layout to the Toolbar to make it more troublesome.

"Ooh so I have to close my keyboard "only" to see the icon preview layout when I've edited the XML?" really ridiculous.

**Comment by deepkrg17** [comment]
It's also in the options menu. You can run from there if you don't want to close your keyboard.

**Comment by QiubyZ** [comment]
> It's also in the options menu. You can run from there if you don't want to close your keyboard.

I better choose hide keyboard. by pressing the back button.

**Comment by QiubyZ** [comment]
Okay, if that is the case.
