### ISSUE TITLE
Some needed improvements

### ISSUE THREAD

**Issue by dhaigit** [itsaky/AndroidIDE#41]
1) In the editor, if we want to edit at a location lower than the height of the onscreen keyboard and tap there, the keyboard shows up and covers the place where we are editing. The editor should readjust so the text appears just above the keyboard.

2) It would be nice if we could select the whole line of text quickly. At the moment, we can only quickly select either one word or the entire file, which is not that convenient. I'm used to edit in another IDE where I can gradually "expand" the selection from a word, group of words, whole line, or everything.

3) At the moment, to look for and fix errors we have to:

-go through the sea of messages and fish for the errors
-make a mental note where it is in the build outputs so we know which is already done and can go back to it
-look for the name of the file the error is in
-look for the line and place of the error
-chant the line numer repeatedly in head so we don't forget (lol)
-go to the filetree, look for the file and open it
-oh no, what was the number again??
-go back to build outputs to look for the line number
-go back to the file to find the error
-fix error
-rinse and repeat for the rest of the errors

It's very tedious. The sooner we have a tab with a list of only errors where we can tap on each to go straight to the specific error, the better.

4) There should be a button at a convenient place where we could quickly press to check only what we just changed for typos or syntactical errors. We don't want to assemble, build, or quick run for small changes. (Real time checking seems too slow at the moment, and sometimes working sometimes not)

**Comment by Etanarvazac** [comment]
I will say the Hacker's Keyboard on Google Play does have a workaround for text selection. Still may be a bit tedious, but it will grant you selecting a whole line. The other option (if your device supports it) is to use a physical keyboard by Bluetooth or direct USB (USB to your cgarger port adapters can be found on Amazon or a local superstore). Below is instructions for the on-screen keyboard.

1. [Install Hacker's keyboard on Google Play](https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard)
2. In the settings for the keyboard, look for 5-row layout OR landscape full keyboard and enable it
3. Reurn to the editor and you should have arrow keys. Simply press `Shift` and the arrow key in the direction of highlight. It works in most editors (even those that don't show text is being highlighted).
Again it is tedious as you must hit shift after each arrow key press. Sometimes you can also get away with `Ctrl` and `Shift` followed by an arrow. This allows a whole word vs 1 character.

Landscape:
![Screenshot_20220103-153749_GitHub.jpg](https://user-images.githubusercontent.com/55290878/147979588-791991df-0971-40a1-bd11-c0bcf04acb7e.jpg)
Portrait:
![Screenshot_20220103-155135_GitHub.jpg](https://user-images.githubusercontent.com/55290878/147979807-024af253-9abe-4ff3-8426-f3cc28c5b5c0.jpg)

**Comment by dhaigit** [comment]
Thanks for the suggestions but I'm using this app as a total mobile, use-anywhere solution. If I wanted to connect a keyboard to a phone, I might as well use the big and powerful desktop pc. Imagine typing on a real keyboard, hunching your back and looking at a tiny phone from the same distance as that of a monitor on your desk. It's not going to work out too well.

About using the other onscreen keyboard, it could work for selecting the whole line. A built-in solution is a lot better though, as the app can also parse the line for logical groups of expressions and let us "expand" onto each.

**Comment by Etanarvazac** [comment]
Yes, implemented would be better. At least there is a work-around until such feature is added.

**Comment by itsaky** [comment]
You have some really good suggestions, I'll implement (and fix) it but it will take some time.

**Comment by dhaigit** [comment]
The errors log (diagnostics) lets us know if there are errors in our code and lets us tap on it to go straight to the error. Great, but we have to open a file with errors in order to see them. 

In a project where there are dozens, hundreds or more files, and there are errors in multiple files, we still can't find and jump to a specific error without having to go through the build output first to find the file names.

So, the app still has not yet completely fixed the "tedious" problem when trying to debug our apps.

**Comment by itsaky** [comment]
Compilation of java files is handled by Gradle. So we cannot get all the errors at once. However, when you open a java file, the language server analyzes the code and sends diagnostics to the app. As soon as you close that file, the diagnosics are cleared and the language server does not bother to analyze that file again to save time and memory.

There is a way to provide diagnostics of all files, that is, using Eclipse's JDT Compiler within the IDE. But that would unnecessarily increase memory usage. So, I'm not gonna implement it anytime soon.
