### ISSUE TITLE
Cannot resolve symbol R

### ISSUE THREAD

**Issue by mohaniTech** [itsaky/AndroidIDE#416]
### What happened?

hi guys

i'm new to the programming world and
i wanted to learn some java and xml before i start Kotlin. i was trying to recreate some very small projects from youtube clips and web articles while i'm still learning java. so what i tried so far is to add a Fragment to an Activity by following a one-year old youtube video, but the problem is  that, the fragment Class can't locate or recognize the layout file of the Fragment:
``` java
@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                         Bundle savedInstanceState) {

    return inflater.inflate(R.layout.name_fragment, container, false);
```
because there is no resource Class in my project. i tried to import: 
```
import <my package>.R;
```
but R.Class doe's exist. 

what should i do? i can't use ViewModel example project that you prepared, cause all videos and articles i found don't use viewmodel.  there are some other errors in  Diagnostics like: 
 ```
OnCreateView(....); is deprecated... 
```
do i need  jdk 8 or something?
i really need this to follow old tutorials. 

i dont know if i'm reporting a bug or requesting a feature. never posted on GitHub before.

this app is good for new learns who don't have pc. thanks for the IDE!

sorry for my bad English.

### What's the expected behavior?

just wanted a fragment Class to recognize its layout file.  or resources dir and R.Classes to be generated Automatically.

### What version of AndroidIDE you're using?

v2.1.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MatheusTGamerPro** [comment]
I downloaded the latest build of Android IDE, and try to install the SDK again. About `OnCreateView (....) Is deprecated`, this is a warning that the IDE will send you when a command, method, function, classes is already obsolete. i.e. not in use, so consider `deprecated` warnings as warnings, but most likely there are other newer functions to use, so always check the Documentation to check if a component has not updated.

**Comment by mohaniTech** [comment]
> 
> If it doesn't work in either case, build the app once with a `clean-build` from Gradle, going into the build options. This will make Gradle install all dependencies locally again, and possibly update the **R** class.

believe me i did that already. i even reinstalled the app. it builds and installs all the dependecies successfully. but there is  always that red underline on `R.layout.name_fragment`. Activities only project works fine so far, but it's when you try to create a fragment class with its layout and try to show the layout. it simply can't find the layout cause **R** Class doesn't exist. there is always this  `package R doesn't exist` error.  Gradle doesn't generate R classes automatically. 

can you please confirm it. create one activity and one fragment manually then add the fragment to the activity. don't use  `Fragment + ViewModel` example.

**Comment by BanDroid** [comment]
onCreateView is deprecated, put your layout id in constructor

public MyFragment() {
  super(R.layout.my_fragment_layout);
}

**Comment by mohaniTech** [comment]
guys! i found the solution. there are no such R classes but only Binding classes. so i'm supposed to import `Binding Class` not `R Class` like this:
```java
import com.mohanitech.fragmentexample.databinding.HomeFragmentBinding;
```
and inflate the layout for the fragment like this:
```java
HomeFragmentBinding binding = HomeFragmentBinding.inflate(inflater, container, false);
        return binding.getRoot();
```
instead of this:
```java
return inflater.inflate(R.layout.home_fragment, container, false);
```
i  compiled the app, installed and working fine. so from now on i will do this when following old tutorials. 

thanks for your help guys!
