### ISSUE TITLE
Some bugs in code completion

### ISSUE THREAD

**Issue by dhaigit** [itsaky/AndroidIDE#42]
1. There is an issue with the case sensitivity of first letter of class names. For example, when typing "toa", we expect the "Toast" class to show up on the list, but it doesn't. We need to type "Toa", then it shows up. Normal variable names seem to show up as expected.

2. After typing "Toastt", for example, then, a backspace to remove the extra "t", class "Toast" doesn't show as expected. The app needs to also update the list after every backspace.

3. A class name of a class in its own file is being included in a code completion search, but a class defined in the same file as the main class is not.

There are times when the completion service crashes and no list would show up when we type, but that's a different story. These issues listed here are for when the completion service is up and running.

**Comment by dhaigit** [comment]
Would you point me to the right place in the project where I might be able to address number 3 from above? Completion needs to recognize multiple classes within the same .java file. I'd like to find

**Comment by dhaigit** [comment]
I'm going to put an example for number 3 from above so it would be clearer to understand what I mean.

MainActivity.java:

public class MainActivity extends AppCompatActivity {
    ...
}

class ClassInSameFile {
    ...
}

We need autocompletion to recognize and list out the ClassInSameFile class when we start typing "Cl..."

The compiler has no problem seeing them and compiles without errors. It's just that autocompletion doesn't see them.

**Comment by itsaky** [comment]
Fixed in 67e95f5cd6458a501ade652bb557a50c70a4bebb.

**Comment by dhaigit** [comment]
Shouldn't we have waited until we also have the other two above, then close?

1. Preference setting to turn on/off first letter case sensitivity in autocompletion (or some kind of logical results sorting to avoid having to hit that SHIFT key every single time)

My reason is that, let's say I have a local variable "toast".

If I typed "toa", I would only have local variable "toast" shown and not "Toast". If I typed "Toa", I would have both "Toast" and "toast".

For me, it's better to have the latter completion list since I could pick from either "Toast" or "toast". Currently, however, to have this prefered list, I need to hit the SHIFT key. Every. Single. Time.

2. Refresh autocompletion list when backspacing a letter.

@itsaky
Shouldn't I have (or in the future) posted each in a separate post? That would result in a long list of open issues, wouldn't it?

**Comment by itsaky** [comment]
> If I typed "toa", I would only have local variable "toast" shown and not "Toast". If I typed "Toa", I would have both "Toast" and "toast"

That might increase the completion response timing as it will keep finding list of classes.

> Refresh autocompletion list when backspacing a letter.

The completion list is refreshed. See this :

https://user-images.githubusercontent.com/46931079/151099029-0c24a355-9b3c-4609-b775-8979ce68fda8.mp4

**Comment by dhaigit** [comment]
I just tested out the build. Even though the auto typed classes show, I only need to match the first uppercase letter then type any random letters after that.

For example, let's say I have:

class MySameFileClass {
    ...
}

I could type "Mxxxxxxxxx", or "Myyyyyy", or "Mblahblahblah", and the list would include MySameFileClass class.

**Comment by dhaigit** [comment]
>That might increase the completion response timing as it will keep finding list of classes.
>
That's how the IDE is currently. If I typed "Toa", it shows both. So for a preference, it could show both if "toa" is entered. Nothing extra is done except we don't need to type SHIFT at the start of everything.

**Comment by itsaky** [comment]
Okay. I'll add it.

**Comment by itsaky** [comment]
A preference has been added. It is diabled by default. You can enable it in `Preferences -> Editor -> Match completions in lower case`. When enabled, java completion provider will use lower case letters to match partial names.

**Comment by dhaigit** [comment]
>The completion list is refreshed.
>
The clip you showed doesn't demonstrate what I was referring to.

-Type "Toastt" (Toast class was spelled wrong so it does not appear)
-Now backspace to delete the (extra) "t" at the end
-Repeat adding and removing that extra "t"

The expected behavior is that after removing the extra "t", the spelling is correct and it should show the Toast class. But it doesn't.
