### ISSUE TITLE
[Feature]: Add decompile and recompile tasks

### ISSUE THREAD

**Issue by Issasafar** [itsaky/AndroidIDE#423]
### Feature description

Decompile the apks into "editable"  java and xml 

### What version of AndroidIDE you're using?

v2.1.1

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MrIkso** [comment]
It's not a tool for editing apk

**Comment by Issasafar** [comment]
> It's not a tool for editing apk

I know but why not
