### ISSUE TITLE
Missing files/folders

### ISSUE THREAD

**Issue by ericwomer** [itsaky/AndroidIDE#424]
Started a project and ide can't find files or folders

**Comment by ericwomer** [comment]
GradleBuildService        I   Showing notification to user... 
EditorActivity            I   Gradle build service has been started... 
FileTreeFragment          E   Unable to restore tree state  treeState=null  treeView=com.unnamed.b.atv.view.AndroidTreeView@d88ef7d 
FileTreeFragment          E   Unable to restore tree state  treeState=null  treeView=com.unnamed.b.atv.view.AndroidTreeView@d88ef7d 
GradleBuildService        I   Starting tooling API server... 
GradleBuildService        E   Unable to start tooling API server 
GradleBuildService        E  java.io.IOException: error=2, No such file or directory
GradleBuildService        E  	at java.lang.UNIXProcess.forkAndExec(Native Method)
GradleBuildService        E  	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
GradleBuildService        E  	at java.lang.ProcessImpl.start(ProcessImpl.java:141)
GradleBuildService        E  	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
GradleBuildService        E   Caused by: java.io.IOException: Cannot run program "/data/data/com.itsaky.androidide/files/usr/opt/openjdk/bin/java" (in directory "/data/data/com.itsaky.androidide/files/home"): error=2, No such file or directory
GradleBuildService        E  	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
GradleBuildService        E  	at com.itsaky.androidide.shell.CommonProcessExecutor.newProcess(CommonProcessExecutor.java:85)
GradleBuildService        E  	at com.itsaky.androidide.shell.CommonProcessExecutor.newProcess(CommonProcessExecutor.java:74)
GradleBuildService        E  	at com.itsaky.androidide.shell.CommonProcessExecutor.execAsync(CommonProcessExecutor.java:65)
GradleBuildService        E  	at com.itsaky.androidide.shell.CommonProcessExecutor.execAsync(CommonProcessExecutor.java:54)
GradleBuildService        E  	at com.itsaky.androidide.services.GradleBuildService$ToolingServerRunner.run(GradleBuildService.java:473)
GradleBuildService        E  	at java.lang.Thread.run(Thread.java:1012)
GradleBuildService        E  
GradleBuildService        E  
FileTreeFragment          E   Unable to restore tree state  treeState=  treeView=com.unnamed.b.atv.view.AndroidTreeView@9fc75e3 
FileTreeFragment          E   Unable to restore tree state  treeState=  treeView=com.unnamed.b.atv.view.AndroidTreeView@cd6b03e 
FileTreeFragment          E   Unable to restore tree state  treeState=  treeView=com.unnamed.b.atv.view.AndroidTreeView@8ae3ee0 
FileTreeFragment          E   Unable to restore tree state  treeState=  treeView=com.unnamed.b.atv.view.AndroidTreeView@5407325 
FileTreeFragment          E   Unable to restore tree state  treeState=  treeView=com.unnamed.b.atv.view.AndroidTreeView@4d4b63d

**Comment by deepkrg17** [comment]
Have you installed openjdk and other build tools?

**Comment by deepkrg17** [comment]
Have you installed openjdk and other build tools in AndroidIDE?

**Comment by ericwomer** [comment]
Yeah, just read the instructions, saw the install script part, go ahead and close this as solved.
