### ISSUE TITLE
quick request about logs panel

### ISSUE THREAD

**Issue by dhaigit** [itsaky/AndroidIDE#48]
Could you make a quick modification to the logs panel so that when dragging it up  we could also pin it at a height we prefer?

It would be very helpful to be able to see the messages in real time. I'm thinking of making my keyboard partially transparent so that I could be able to see the logs while typing in the editor at the same time.

**Comment by itsaky** [comment]
By "logs panel", you mean this? : 
![Screenshot_2022-01-11-09-40-38-19_9ad8e654efd333b66ab21513aa36e36c](https://user-images.githubusercontent.com/46931079/148879886-0066e5c5-6cdf-4c15-bfab-a936d9366ef0.jpg)

**Comment by dhaigit** [comment]
Yes, that's the one. Didn't know what to call it. Lol.

**Comment by itsaky** [comment]
This will not be fixed as `SymbolInputView` replaces that panel. I could consider something else for showing the build status instead of making both of them visible.

**Comment by dhaigit** [comment]
I think we're talking about the wrong one here. In the image you show, I was referring to the one under that says "...build outputs, logs, and more" (I didn't want to call it build output because it also has "logs and more", lol.

It's the one that we drag up and it would slide all the way up. What I would like it to do is being able to stop at any height we want. Currently, with any amount of dragging, it automatically scrolls itself all the way to the top, fills the whole screen, and covers the editor.

Actually, it happened once or twice to me, when that dragged panel would get stuck in the middle on its way going up. At that time, I could see both the editor and that the panel at the same time. That was how I got the idea.
