### ISSUE TITLE
Comments shouldn't be checked for errors/warnings and hints

### ISSUE THREAD

**Issue by MarvinStelter** [itsaky/AndroidIDE#5]
Code that is in a comment should not be inspected for errors 

![Screenshot_2021-08-07-18-36-13-431_com.itsaky.androidide.jpg](https://user-images.githubusercontent.com/41212885/128613837-a37d3fa1-bc1e-4e65-b28d-1ac16310e278.jpg)

**Comment by itsaky** [comment]
Comments aren't really checked for errors and warnings.
