### ISSUE TITLE
Possible reasons for build tools installation failure?

### ISSUE THREAD

**Issue by dhaigit** [itsaky/AndroidIDE#75]
What are some possible reasons for when the initial installation of Build Tools fails?

/////
Installation failed

Installation process terminated with exit code 1. Make sure you downloaded the build tools from original sources.

You could try to clear data of AndroidIDE and install again.
/////

They are the exact same original files that work fine on other devices or at other times of installation.

**Comment by itsaky** [comment]
A build tools installation might fail if the process does not exit with `exit code 0` (See [this](https://github.com/itsaky/AndroidIDE/blob/7aa2420a5fb2e4a9ac154e8b9522ba682cb7e60e/app/src/main/java/com/itsaky/androidide/DownloadActivity.java#L150)).

Other reasons :
- The user selects a folder which has no installable archives, the installation will fail. See [this](https://github.com/itsaky/AndroidIDE/blob/7aa2420a5fb2e4a9ac154e8b9522ba682cb7e60e/app/src/main/java/com/itsaky/androidide/DownloadActivity.java#L190).
- If the IDE was not able to write the installation script. See [this](https://github.com/itsaky/AndroidIDE/blob/7aa2420a5fb2e4a9ac154e8b9522ba682cb7e60e/app/src/main/java/com/itsaky/androidide/DownloadActivity.java#L220).
- An `IOException` occurs while creating or executing the installation process. See [this](https://github.com/itsaky/AndroidIDE/blob/7aa2420a5fb2e4a9ac154e8b9522ba682cb7e60e/app/src/main/java/com/itsaky/androidide/DownloadActivity.java#L138).
