### ISSUE TITLE
[BUG] crash on armv7a device

### ISSUE THREAD

**Issue by masterjavaofficial** [itsaky/AndroidIDE#76]
AndroidIDE crashed on armv7a after I open Terminal, although installing the SDK, JDK, sysroot & aapt2 successfully.

**To Reproduce**
You need a armv7a architechture device to reproduce this error.

1. Download and install the latest version of AndroidIDE from Github CI actions (because the one you get from the androidide.com site is incompatible with armv7a architectures)
2. Download all the tools (aapt2, sysroot, Android SDK, OpenJDK) of 32 bit version from the official website, put those all tar.xz archives into one single directory.
3. Install those tools into the AndroidIDE by starting the app, granting permission to internal storage, picking the directory and clicking install. The installation completes successfully.
4. Restart the app, click on Terminal button, and boom! The error grasps you!

**Expected behavior**
I should be able to see the beautiful terminal!

**Screenshots**
N/A

**Details:**
AndroidIDE crash report
Manufacturer: Xiaomi
Device: Redmi8A
App version: 2.0-beta (200)

Stacktrace:  `android.system.ErrnoException: open failed: EACCES (Permission denied) 	at libcore.io.Linux.open(Native Method) 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167) 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252) 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167) 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7461) 	at libcore.io.IoBridge.open(IoBridge.java:483)  Caused by: java.io.FileNotFoundException: /data/data/com.itsaky.androidide/files/sysroot/bin/less: open failed: EACCES (Permission denied) 	at libcore.io.IoBridge.open(IoBridge.java:497) 	at java.io.FileOutputStream.<init>(FileOutputStream.java:235) 	at java.io.FileOutputStream.<init>(FileOutputStream.java:186) 	at com.itsaky.androidide.utils.BootstrapInstaller.lambda$doInstall$0(BootstrapInstaller.java:121)  Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: /data/data/com.itsaky.androidide/files/sysroot/bin/less: open failed: EACCES (Permission denied) 	at com.itsaky.androidide.utils.BootstrapInstaller.lambda$doInstall$0(BootstrapInstaller.java:165) 	at com.itsaky.androidide.utils.BootstrapInstaller$$ExternalSyntheticLambda0.run(Unknown Source:4) 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1663)  Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: java.io.FileNotFoundException: /data/data/com.itsaky.androidide/files/sysroot/bin/less: open failed: EACCES (Permission denied) 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:278) 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:284) 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1666) 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1655) 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:285) 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1155) 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1993) 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1941) 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)`

**Additional context**
N/A

**Comment by itsaky** [comment]
See #59.
