### ISSUE TITLE
Code highlight is not obvious

### ISSUE THREAD

**Issue by guitar-girl** [itsaky/AndroidIDE#77]
These codes don't look obvious.
![IMG_20220124_124125](https://user-images.githubusercontent.com/98469154/151177114-9e608fba-6871-4025-9e21-da9497c047e5.jpg)
Is it possible to support code highlight color customization?

**Comment by itsaky** [comment]
The method call syntax highlight issue was fixed in 8102390525acabb1932cd1657da77e5e53f4c9c4.

It is not currently possible to cutomize the color scheme without modifying source code. It'll be available later.
