### ISSUE TITLE
Editor: messy quickscale(doubletap-swipe) zooming

### ISSUE THREAD

**Issue by dhaigit** [itsaky/AndroidIDE#78]
Issues:
-sometimes text gets selected unintentionally
-zooming progress gets interrupted, stuck, or is misbehaving, if zooming past min or max (doubletap then swipe finger all the way down or up)

Suggestions:
When quickscale is activated, we should:
-disable cursor movements (maybe also need to save current location first and put it back when quickscale is done?)
-don't activate onscreen keyboard if it's not already active
-maybe lower the zooming speed a tiny bit (or even a set speed in preference)

**Comment by dhaigit** [comment]
>maybe lower the zooming speed a tiny bit (or even a set speed in preference)
>
I'm going to take back what I said about the "too fast zooming speed"

It is more of an issue about the responsiveness when zooming (i.e. how instant the zooming action is, following the moving finger.)

**Comment by itsaky** [comment]
The editor has been updated. Check if the issue exists in the latest commits.

**Comment by dhaigit** [comment]
>-zooming progress gets interrupted, stuck, or is misbehaving, if zooming past min or max (doubletap then swipe finger all the way down or up)
>
This issue is still there. To reproduce:

-Double tap and slide finger all the way up until text can't get any smaller.
-Slide finger back down, then up and down again a few times to see if text size changes accordingly. You would now notice that the zoomig is misbehaving and might even get stuck.

Also, I see that the normal screen dragging action (with single tap dragging) is mixed with the quickscale zooming action (with double tap dragging). This is making the zooming moments weird and shaky.

Like I have suggested before, I think the moment quickscale zooming is activated, we need to disable anything else that could move the screen or cursor. It also should not have done a doubletap text selection before the zooming starts.

And last, if the onscreen keyboard was not shown before the quickscale zooming starts, we should make sure the keyboard is not shown while the zooming is in action.

**Comment by itsaky** [comment]
Fixed by @Rosemoe in https://github.com/Rosemoe/sora-editor/commit/fa8d5f43c73d2e2f44f83d62ed777f8ba233b951.
