### ISSUE TITLE
Easier access to (copy/paste, ...)

### ISSUE THREAD

**Issue by dhaigit** [itsaky/AndroidIDE#84]
We need easier and closer access to copy, paste, cut, and expand a text selection.

Currently, after making a selection, the finger has to travel a l l  t h e  w a y  u p  t h e r e to the three-dotted menu to find what we need.

We need those actions to be selectable right next to the cursor or text selection, and in an intuitive way.

**Comment by itsaky** [comment]
I could add an option to use popup window for the text actions. That window will be shown just above the cursor. But, in this case, I'm not sure how to show other options. Should I place them vertically or make them horizontally scrollable?

**Comment by dhaigit** [comment]
Could we try a vertical popup first? We'll test that out to see if it's good enough or better horizontal.

Here are my suggestions:

We're mostly right-handed. So let's say after double-tapping or long-pressing, we have a word selected. We display a vertical popup right next to the right handle. We need to pick a good vertical height to put it so that the thumb doesn't need to reach too far up or down.

Remember to temporarily hide the popup when the user is dragging the handles to modify the selection. Show it again after the handle is released, but move it to right where the thumb just let go of the handle.

I think we might also need to make the popup semi-transparent because if a modified selection (after a drag or expand) is longer than a line, the popup would block the text.

**Comment by dhaigit** [comment]
>We display a vertical popup right next to the right handle.
>
Actually, I think referencing the tapped coordinate would be better since the selected word could be long and the right handle would be way off to the right and far away from the finger.

**Comment by itsaky** [comment]
Added in a42cbdc436cce49b2f0780d6c10a3b3a8ac404b9.
