### ISSUE TITLE
Autocompletion optimization ideas

### ISSUE THREAD

**Issue by dhaigit** [itsaky/AndroidIDE#85]
Could we not make the API info load on default in a completion popup, but let it say "Show API info" as a place holder? Only when that area is tapped, it would then load the info and show it.

Do you think that would make it a bit faster?

**Comment by itsaky** [comment]
Including a clickable view in the completion list is not a good idea.

These type of topics should be discussed in [Telegram](https://t.me/androidide_discussions).
