### ISSUE TITLE
Method paramters index out of bound 

### ISSUE THREAD

**Issue by dhaigit** [itsaky/AndroidIDE#89]
This bug was mentioned by @Smooth_E in #87.
I can confirm this crashing bug.

It happens when an index higher than the number of parameters in a method is used.

To reproduce, pick any method that you usually use. I'm going to give you a one-key-crashing-example. Lol.

1. Open a simple project (or any project) and wait for it to be done with the initial task.

2. Go to the line...
setContenView(R.layout.activity_main);
...and type a comma right after "...main"

3. Crash

**Comment by itsaky** [comment]
Already fixed in 1f09cc07921432a730a2b95d34174542c27041e0.
