### ISSUE TITLE
diagnostics popup is one step too late?

### ISSUE THREAD

**Issue by dhaigit** [itsaky/AndroidIDE#90]
When we type, for example, a random word that's not a recognized identifier, "abcxyz", the popup should show right after each letter that we type, but it doesn't. Only after we backspace the last letter, it then show the popup. We now have "abcxy" but the diagnostics is for "abcxyz"

The issue does not only appy for random words but any word and it's hard to explain the "one step too late" part.

Let me give another example:
1. Open a simple project and make sure it has no errors.
2. In OnCreate for example, type "String s = new String();" without quotes.
3. You should see no red-underlining words anywhere at the moment.
3. Position cursor after "w" of "new"
4. Tap backspace to delete "w"
5. The Editor still wouldn't red-underline "ne" to indicate that there's an error (it's because it is one step too late in analyzing and thinks it's still "new"
6. Type "w"
7. Now the Editor puts a red line under "new" as it thinks it's "ne" (again, one step too late)

I hope that's enough to clearly understand this issue.

**Comment by itsaky** [comment]
Fixed.
