### ISSUE TITLE
first issue from #41

### ISSUE THREAD

**Issue by dhaigit** [itsaky/AndroidIDE#91]
>In the editor, if we want to edit at a location lower than the height of the onscreen keyboard and tap there, the keyboard shows up and covers the place where we are editing. The editor should readjust so the text appears just above the keyboard.
>
This seems to have been addressed in the latest build. However, the scrollbars should hide right away instead of after a second or two. They're also blocking the text. They dismiss right away when we put cursor higher than keyboard height, so it should do the same when we place cursor lower than keyboard height.

**Comment by MarvinStelter** [comment]
I will close this issue now, please create only one "issue" for improvents!
