### ISSUE TITLE
Improvements for vertical floating text actions popup

### ISSUE THREAD

**Issue by dhaigit** [itsaky/AndroidIDE#94]
To make screen easier to see and move around while doing the actions:

1. Add an alpha slider preference for the popup
and/or
2. Anchor the popup to the right edge (but keep that thumb reachable vertical distance)
3. Reduce the popup's width to about a thumb's width (maybe by replacing caps with intuitive icons that have text hints when holding down)
4. Rearrange order of actions: (customizable order is even better)
[paste     ] (1 higher)
[expand  ] (closest to thumb)
[copy      ] (1 lower)
[cut         ] (2 lower)
[select all] (3 lower)
...

[EDIT 1]
After more testing, I see that the current popup actions layout makes sense too, except for the access position of "select all" next to "expand". "Select all" is not used that often, at least not more than copy, cut and paste. Also, the position of the popup sometimes shows up a bit far away from the thumb. That was why I didn't think it made sense at first.

For "expand" action, I'm thinking since we already have "select all", maybe we should limit the max expansion to a line or a code block only. This is also because the entire file got selected unintentionally many times for me when using the "expand" action. That action needs to be "smarter" when making an expansion.

Another thing that would be hard to solve is that, very often, the popup is blocking the right text selection handle.[EDIT] This could be solved be leaving the selection selected when dismissing the actions popup.

**Comment by MarvinStelter** [comment]
I will close this issue now, please create only one "issue" for improvents!
