### ISSUE TITLE
No file closing confirmation (and asking to save file) when closing a project

### ISSUE THREAD

**Issue by dhaigit** [itsaky/AndroidIDE#98]
When we select to close a project, a popup shows up confirming the stopping of gradle daemons, but no confirmation for unsaved files. I think that confirmation does popup but it then autonaticaly disappears right away.

Also, in a file close confirmation, it would be better if we arrange the text to put the file name(s) first, then (maybe even with a blank line to separate them) the question "Would you like to save them before closing?" so that it would be right above the response of "No" or "Yes". That way, we could quickly and precisely give a response without having to look for the question (to make sure) in the relatively long [paragraph].

**Comment by itsaky** [comment]
The IDE now asks user to save unsaved files before closing the project (1adf116d285d7e4470656594b2d9f482e9821b73).
